openapi: 3.0.3
info:
  title: Todo List
  version: 1.0.0
servers:
    - url: http://127.0.0.1:5000/

paths:
  /todo-list:
    get:
      description: Returns a list of all todo lists.
      responses:
        '200':
          description: Succesful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameter1:
                    type: array
                    description: the first parameter
                  parameter2: 
                    type: array
                    description: the second parameter
    post:
      description: Adds a new todo list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parameter1:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameter1:
                    type: array
                    items:
                      type: string
              example:
                parameter1:
                  - "Task 1"
                  - "Task 2"
                  - "Task 3"
  
  /todo-list/{list_id}:
    get:
      description: Returns all entries of one todo lists.
      parameters:
        - in: path
          name: list_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Succesful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameter1:
                    type: string
                    description: The first entry of requested todo list
                  parameter2:
                    type: string
                    description: The first entry of requested todo list

        '404':
          description: ID not found
  
    delete:
      description:  Deletes one todo list with all its entries
      parameters:
        - in: path
          name: list_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List succesfully deleted
        '404':
          description: ID not found
        '500':
          description:  Error while writing

    patch:
      description:  Updates one existing list.
      responses:
        '200':
          description: List succesfully updated
        '404':
          description: ID not found
        '500':
          description:  Error while writing
  
  /todo-list/{list_id}/entry:
    post:
      description: Adds one entry to an existing lists.
      parameters:
        - in: path
          name: list_id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List succesfully updated
        '404':
          description: ID not found
  
  /entry/{entry_id}/:
    patch:
      description: Updates one existing entry
      responses:
        '200':
          description: entry succesfully updated
        '404':
          description: ID not found
        '500':
          description:  Error while writing

    delete:
      description: Deletes one entry in a list
      responses:
        '200':
          description: entry succesfully deleted
        '404':
          description: ID not found
        '500':
          description:  Error while writing
        


                  